name: Build and deploy ASP.Net Core app to Azure Web App - win23jsbackend-anggelick

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: List contents of root directory
        run: dir
        shell: pwsh

      - name: List contents of Frontend directory
        run: dir ./Frontend
        shell: pwsh

      - name: List contents of Frontend/Frontend directory
        run: dir ./Frontend/Frontend
        shell: pwsh

      - name: Build with dotnet
        run: dotnet build ./Frontend/Frontend/Frontend.csproj --configuration Release
        shell: pwsh

      - name: Publish with dotnet
        run: dotnet publish ./Frontend/Frontend/Frontend.csproj --configuration Release -o ${{ github.workspace }}/myapp
        shell: pwsh

      - name: List contents of myapp directory after publishing
        run: dir ${{ github.workspace }}/myapp
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List contents of workspace after downloading artifact
        run: dir ${{ github.workspace }}
        shell: pwsh

      - name: List contents of myapp directory after downloading
        run: dir ${{ github.workspace }}/myapp
        shell: pwsh

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'win23jsbackend-anggelick'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_655B7A3468A646D49190D078FC19B087 }}
